    dc.b "SEGA GENESIS    "      ; Console name
    dc.b "(C)SEGA 2025.MAR"      ; Copyright/date
    dc.b "HELLO WORLD DEMO                                 " ; Domestic name
    dc.b "HELLO WORLD DEMO                                 " ; International name
    dc.b "GM XXXXXXXX-XX"        ; Version number
    dc.w $0000                   ; Checksum
    dc.b "J               "      ; I/O support
    dc.l $00000000               ; ROM start address
    dc.l $00100000               ; ROM end address
    dc.l $00FF0000               ; Start of RAM
    dc.l $00FFFFFF               ; End of RAM
    dc.l $00000000               ; SRAM enabled
    dc.l $00000000               ; Unused
    dc.l $00000000               ; Unused
    dc.l $00000000               ; Unused
    dc.b "                                        "         ; Notes
    dc.b "JUE             "      ; Country codes