; Reference style M68K instruction tests

; This file contains test cases for M68K instructions in a reference style format
; Generated by script on 2025-05-02T22:41:58.007Z

; Immediate instructions
	ori.b	#42,d0
	ori.b	#42,(a0)
	ori.b	#42,ccr	; TODO: should check if this is allowed
	ori.w	#42,d0
	ori.w	#42,(a0)
	ori.w	#42,sr	; TODO: should check if this is allowed
	ori.l	#42,d0
	ori.l	#42,(a0)
	andi.b	#42,d0
	andi.b	#42,(a0)
	andi.b	#42,ccr	; TODO: should check if this is allowed
	andi.w	#42,d0
	andi.w	#42,(a0)
	andi.w	#42,sr	; TODO: should check if this is allowed
	andi.l	#42,d0
	andi.l	#42,(a0)
	subi.b	#42,d0
	subi.b	#42,(a0)
	subi.w	#42,d0
	subi.w	#42,(a0)
	subi.l	#42,d0
	subi.l	#42,(a0)
	addi.b	#42,d0
	addi.b	#42,(a0)
	addi.w	#42,d0
	addi.w	#42,(a0)
	addi.l	#42,d0
	addi.l	#42,(a0)
	eori.b	#42,d0
	eori.b	#42,(a0)
	eori.b	#42,ccr	; TODO: should check if this is allowed
	eori.w	#42,d0
	eori.w	#42,(a0)
	eori.w	#42,sr	; TODO: should check if this is allowed
	eori.l	#42,d0
	eori.l	#42,(a0)

; Bit manipulation instructions
	bchg	d0,d1
	bchg	d0,(a0)
	bchg	#0,d1
	bchg	#0,(a0)
	bclr	d0,d1
	bclr	d0,(a0)
	bclr	#0,d1
	bclr	#0,(a0)
	bset	d0,d1
	bset	d0,(a0)
	bset	#0,d1
	bset	#0,(a0)
	btst	d0,d1
	btst	d0,(a0)
	btst	#0,d1
	btst	#0,(a0)

; Move instructions
	move.b	d0,d1
	move.w	d0,d1
	move.l	d0,d1
	move.w	d0,a0
	move.l	d0,a0
	move.b	(a0),d0
	move.w	(a0),d0
	move.l	(a0),d0


end	; End of tests
